CREATE TABLE IF NOT EXISTS Classe1 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL,
    CLASSE1 TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Classe2 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL,
    CLASSE2 TEXT NOT NULL
);